name: CI - Todo Typescript API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2 
    - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './docker-compose.yml'
    - run: yarn test
