name: typeORM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - run: yarn install
  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: DerYeger/yarn-setup-action@master
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: './docker-compose.yml'
        node-version: 16
    - run: yarn test
